services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=sqlite:///items.db
      - DEBUG=True
    develop:
      watch:
        - action: sync
          path: .
          target: /app
