## Heartbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/heartbeat.docker.yml
#

name: heartbeat

heartbeat.monitors:
- type: http
  id: flask-meds
  service.name: flask-meds
  name: flask-meds
  tags: ["Flask", "Medications"]
  schedule: '@every 5s'
  hosts: ["web:5000"]
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}
  check.request:
    method: GET
  check.response:
    status: [200]

processors:
- add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/heartbeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
